---
title: "W13"
output: html_document
date: "2026-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(tidyverse)
library(here)
library(pdftools)
library(tidytext)
library(textdata) 
library(ggwordcloud)

got_path <- here("got.pdf")
got_text <- pdf_text(got_path)
got_text
got_df <- data.frame(got_text) %>% 
  mutate(text_full = str_split(got_text, pattern = '\n')) %>% 
  unnest(text_full) %>% 
  mutate(text_full = str_trim(text_full))

got_tokens <- got_df %>% 
  unnest_tokens(word, text_full)

got_tokens

got_wc <- got_tokens %>% 
  count(word) %>% 
  arrange(-n)
got_wc

got_stop <- got_tokens %>% 
  anti_join(stop_words) %>% 
  select(-got_text)

got_swc <- got_stop %>% 
  count(word) %>% 
  arrange(-n)
got_swc

got_no_numeric <- got_stop %>% 
  filter(is.na(as.numeric(word)))

got_no_numeric %>% 
  count(word) %>% 
  arrange(-n)

get_sentiments(lexicon = "afinn")


got_afinn <- got_stop %>% 
  inner_join(get_sentiments("afinn"))
got_afinn

got_afinn_hist <- got_afinn %>% 
  count(value)

ggplot(data = got_afinn_hist, aes(x = value, y = n)) +
  geom_col(aes(fill = value)) +
  theme_bw()

got_afinn2 <- got_afinn %>% 
  filter(value == 2)

got_afinn2_n <- got_afinn2 %>% 
  count(word, sort = TRUE) %>% 
  mutate(word = fct_reorder(factor(word), n))

ggplot(data = got_afinn2_n, aes(x = word, y = n)) +
  geom_col() +
  coord_flip() +
  theme_bw()

